In [1]:
import pandas as pd

In [2]:
csfb = pd.read_excel("data/ConfigurationData_2025_08_22_16_43_59.xlsx","CSFALLBACKBLINDHOCFG",skiprows=1)
cellalgo = pd.read_excel("data/ConfigurationData_2025_08_22_16_43_59.xlsx","CELLALGOSWITCH",skiprows=1)
cellhppara = pd.read_excel("data/ConfigurationData_2025_08_22_16_43_59.xlsx","CELLHOPARACFG",skiprows=1)
csfbpolicy = pd.read_excel("data/ConfigurationData_2025_08_22_16_43_59.xlsx","CSFALLBACKPOLICYCFG",skiprows=1)
geranncell = pd.read_excel("data/ConfigurationData_2025_08_22_16_43_59.xlsx","GERANNCELL",skiprows=1)

c:\Users\shamili\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\shamili\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\shamili\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\shamili\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
c:\Users\shamili\AppData\Local\Programs\Python\Python312\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [6]:
cellalgo['concat'] = cellalgo['*eNodeB Name']+cellalgo['*Local cell ID'].astype(str)
cellhppara['concat'] = cellhppara['*eNodeB Name'] + cellhppara['*Local cell ID'].astype(str)
geranncell['concat'] = geranncell['*eNodeB Name'] + geranncell['*Local cell ID'].astype(str)

In [8]:
all = []
hoallowed_dic = {}
cellhoparacfg_dic = {}

In [ ]:
for i in range(len(cellalgo['concat'])):

    enb = cellalgo['*eNodeB Name'].iloc[i]
    lcid = cellalgo['*Local cell ID'].iloc[i]
    con = cellalgo['concat'].iloc[i]

    tcsfb = csfb[csfb['*eNodeB Name'] == enb]
    tcsfbbpoly = csfbpolicy[csfbpolicy['*eNodeB Name'] == enb]
    tgeranncell = geranncell[geranncell['concat'] == con]

    interrathigh = 1 if(tcsfb['Highest priority InterRat'].iloc[0] == "GERAN") else 0
    idlehigh = 1 if(tcsfb['CSFB Highest priority InterRat for Idle UE'].iloc[0] == "GERAN") else 0

    bhpriority = 1 if (tgeranncell['Blind handover priority'].sum() > 1) else 0

    CsfbHoPolicyCfg = str(tcsfbbpoly['CSFB handover policy Configuration'].iloc[0]).split("&")
    poli1 = CsfbHoPolicyCfg[0][-1]
    poli2 = CsfbHoPolicyCfg[1][-1]
    poli3 = CsfbHoPolicyCfg[2][-1]
    IdleModeCsfbHoPolicyCfg = str(tcsfbbpoly['CSFB handover policy Configuration for idle ue'].iloc[0]).split("&")
    poli4 = IdleModeCsfbHoPolicyCfg[0][-1]
    poli5 = IdleModeCsfbHoPolicyCfg[0][-1]
    poli6 = IdleModeCsfbHoPolicyCfg[0][-1]

    hoallowed = str(cellalgo['Handover Allowed Switch'].iloc[i]).split("&")
    for j in range(13):
        hoallowed_dic[f'hoallowed{j}'] = hoallowed[j][-1]
    
    cellhoparacfg = str(cellhppara['Handover Mode switch'].iloc[i]).split("&")
    for k in range(13):
        cellhoparacfg_dic[f'cellhoparacfg{k}'] = cellhoparacfg[k][-1]

    row = [enb, lcid, con, interrathigh, idlehigh, bhpriority,poli1, poli2, poli3, poli4, poli5, poli6] + [hoallowed_dic[f"hoallowed{j}"] for j in range(13)] + [cellhoparacfg_dic[f'cellhoparacfg{k}'] for j in range(13)]
    

    all.append(row)

In [13]:
row_names = ['enb', 'lcid', 'con', 'interrathigh', 'idlehigh', 'bhpriority','poli1', 'poli2', 'poli3', 'poli4', 'poli5', 'poli6'] + [f"hoallowed{j}" for j in range(13)] + [f'cellhoparacfg{k}' for j in range(13)]

In [14]:
row_names

['enb',
 'lcid',
 'con',
 'interrathigh',
 'idlehigh',
 'bhpriority',
 'poli1',
 'poli2',
 'poli3',
 'poli4',
 'poli5',
 'poli6',
 'hoallowed0',
 'hoallowed1',
 'hoallowed2',
 'hoallowed3',
 'hoallowed4',
 'hoallowed5',
 'hoallowed6',
 'hoallowed7',
 'hoallowed8',
 'hoallowed9',
 'hoallowed10',
 'hoallowed11',
 'hoallowed12',
 'cellhoparacfg12',
 'cellhoparacfg12',
 'cellhoparacfg12',
 'cellhoparacfg12',
 'cellhoparacfg12',
 'cellhoparacfg12',
 'cellhoparacfg12',
 'cellhoparacfg12',
 'cellhoparacfg12',
 'cellhoparacfg12',
 'cellhoparacfg12',
 'cellhoparacfg12',
 'cellhoparacfg12']

In [17]:
nall = pd.DataFrame(all, columns=row_names)

In [33]:
nall['con'] = nall['enb'].str[0:6] + nall['lcid'].astype(str)

In [18]:
ref = pd.read_excel("data/sorted cells.xlsx")

In [31]:
ref['con'] = ref['eNodeB Name'].str[0:6] + ref['LocalCell Id'].astype(str)

In [32]:
ref.head(10)

                            eNodeB Name  LocalCell Id      con
0      BDBAD2_GUL00_BADULLA _HUCH_IP_Ba             1  BDBAD21
1       BDDIY3_GUL00_DIYATHALAWA_TXD_Ba             1  BDDIY31
2        BDHAP1_GULM0_Haputhale_Town_Ba             2  BDHAP12
3              BDWEL2_GUL00_WELIMADA_Ba             1  BDWEL21
4     BDTWN1_GUL00_Badulla_Town1_TXD_Ba             2  BDTWN12
5                  BDELL2_GUL00_Ella_Ba             0  BDELL20
6  BDKEP1_GUL00_Keppettipola_Town_IP_Ba             2  BDKEP12
7   BDWTH1_G0L00_BDWTH1_G_Wewathenna_Ba             0  BDWTH10
8              BDWEL2_GUL00_WELIMADA_Ba             1  BDWEL21
9               BDBAD1_GULM0_BADULLA_Ba             1  BDBAD11

In [34]:
common = pd.merge(nall, ref, how="inner")

In [36]:
common.head(100)

,enb,lcid,con,interrathigh,idlehigh,bhpriority,poli1,poli2,poli3,poli4,...,cellhoparacfg12,cellhoparacfg12,cellhoparacfg12,cellhoparacfg12,cellhoparacfg12,cellhoparacfg12,cellhoparacfg12,cellhoparacfg12,eNodeB Name,LocalCell Id
0,BDLUW1_L_LUNUWATTA_Ba,0,BDLUW10,1,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,BDLUW1_GUL00_LUNUWATTA_Ba,0
1,BDWEL2_L_WELIMADA_Ba,0,BDWEL20,1,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,BDWEL2_GUL00_WELIMADA_Ba,0
2,BDWEL2_L_WELIMADA_Ba,1,BDWEL21,1,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,BDWEL2_GUL00_WELIMADA_Ba,1
3,BDWEL2_L_WELIMADA_Ba,1,BDWEL21,1,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,BDWEL2_GUL00_WELIMADA_Ba,1
4,BDWEL2_L_WELIMADA_Ba,1,BDWEL21,1,1,1,1,0,0,1,...,0,0,0,0,0,0,0,0,BDWEL2_GUL00_WELIMADA_Ba,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,ZKDU03_L_Pittugala_Ho,20,ZKDU0320,0,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,ZKDU03_GUL00_Pittugala_Ho,20
96,ZKDU03_L_Pittugala_Ho,21,ZKDU0321,0,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,ZKDU03_GUL00_Pittugala_Ho,21
97,ZKDU03_L_Pittugala_Ho,25,ZKDU0325,0,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,ZKDU03_GUL00_Pittugala_Ho,25
98,ZKDU03_L_Pittugala_Ho,80,ZKDU0380,0,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,ZKDU03_GUL00_Pittugala_Ho,80
99,ZKDU03_L_Pittugala_Ho,82,ZKDU0382,0,0,1,1,0,0,1,...,0,0,0,0,0,0,0,0,ZKDU03_GUL00_Pittugala_Ho,82

In [37]:
new = common.drop(['eNodeB Name','LocalCell Id','enb','lcid','con'],axis=1)

In [38]:
new.to_csv("data/compilied_data.csv",index=False)